//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aux_Precio_Remito
    {
        public Aux_Precio_Remito()
        {
            this.Remito_Detalle = new HashSet<Remito_Detalle>();
        }
    
        // Primitive properties
    
        public int id_codigo { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Remito_Detalle> Remito_Detalle { get; set; }
    
    }
}
