//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Localidad = new HashSet<Localidad>();
        }
    
        public int ID { get; set; }
        public int idProvincia { get; set; }
        public string Nombre { get; set; }
    
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Localidad> Localidad { get; set; }
    }
}
