//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donaciones
    {
        // Primitive properties
    
        public int id_donacion { get; set; }
        public Nullable<int> donante_id { get; set; }
        public Nullable<System.DateTime> fecha_donacion { get; set; }
        public Nullable<int> bioquimica { get; set; }
        public Nullable<int> grupo_id { get; set; }
        public string comentario { get; set; }
    
        // Navigation properties
    
        public virtual tb_GrupoSanguineo tb_GrupoSanguineo { get; set; }
        public virtual tb_Usuarios tb_Usuarios { get; set; }
    
    }
}
