//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donaciones_Historial
    {
        // Primitive properties
    
        public int id_historial { get; set; }
        public Nullable<int> donante_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> grupo_sang_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_Donantes tb_Donantes { get; set; }
        public virtual tb_GrupoSanguineo tb_GrupoSanguineo { get; set; }
    
    }
}
