//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Insumo
    {
        // Primitive properties
    
        public int id_insumo_historial { get; set; }
        public Nullable<int> insumo_id { get; set; }
        public string detalle { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public Nullable<int> cantidad_disponible { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
    
    }
}
