//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomenclador
    {
        public Nomenclador()
        {
            this.Remito_Obra_Social_Detalle = new HashSet<Remito_Obra_Social_Detalle>();
        }
    
        // Primitive properties
    
        public int Codigo { get; set; }
        public string Determinacion { get; set; }
        public string N_I { get; set; }
        public Nullable<decimal> Unidad_Bioquimica { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Frecuencia { get; set; }
        public Nullable<decimal> UB { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Remito_Obra_Social_Detalle> Remito_Obra_Social_Detalle { get; set; }
    
    }
}
