//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido_Detalle
    {
        public int id_notapedido_detalle { get; set; }
        public Nullable<int> insumo_id { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> unidad_medida { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual tb_Insumos tb_Insumos { get; set; }
        public virtual tb_NotaPedido tb_NotaPedido { get; set; }
    }
}
