//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Departamento = new HashSet<Departamento>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Departamento> Departamento { get; set; }
    }
}
