//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito_Detalle
    {
        // Primitive properties
    
        public int id_remito_detalle { get; set; }
        public Nullable<int> remito_id { get; set; }
        public Nullable<int> codigo_id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<decimal> total_venta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        // Navigation properties
    
        public virtual Aux_Precio_Remito Aux_Precio_Remito { get; set; }
        public virtual Remito Remito { get; set; }
    
    }
}
