//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        public Remito()
        {
            this.Remito_Detalle = new HashSet<Remito_Detalle>();
        }
    
        // Primitive properties
    
        public int id_remito { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> numero_remito { get; set; }
        public string razon_social { get; set; }
        public string direccion { get; set; }
        public Nullable<int> cuil_cuit { get; set; }
        public Nullable<int> condicion_iva { get; set; }
        public Nullable<int> condicion_venta { get; set; }
        public Nullable<decimal> total { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Remito_Detalle> Remito_Detalle { get; set; }
        public virtual Tipo_IVA Tipo_IVA { get; set; }
        public virtual Tipo_Venta Tipo_Venta { get; set; }
    
    }
}
