//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito_Obra_Social_Detalle
    {
        // Primitive properties
    
        public int id_os_detalle { get; set; }
        public Nullable<int> nomenclador_id { get; set; }
        public Nullable<int> codigo { get; set; }
        public string determinaciones { get; set; }
        public string NI { get; set; }
        public Nullable<decimal> Unidad_Bioquimica { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> UB { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> remito_os_id { get; set; }
        public Nullable<decimal> total { get; set; }
    
        // Navigation properties
    
        public virtual Nomenclador Nomenclador { get; set; }
        public virtual Remito_Obra_Social Remito_Obra_Social { get; set; }
    
    }
}
