//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito_Obra_Social
    {
        public Remito_Obra_Social()
        {
            this.Remito_Obra_Social_Detalle = new HashSet<Remito_Obra_Social_Detalle>();
        }
    
        // Primitive properties
    
        public int remito_os_id { get; set; }
        public Nullable<int> obrasocial_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<decimal> total { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Remito_Obra_Social_Detalle> Remito_Obra_Social_Detalle { get; set; }
        public virtual tb_ObraSocial tb_ObraSocial { get; set; }
        public virtual tb_Pacientes tb_Pacientes { get; set; }
    
    }
}
