//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Detalle
    {
        // Primitive properties
    
        public int id_stock_detalle { get; set; }
        public Nullable<int> insumo_id { get; set; }
        public Nullable<int> cantidad_disponible { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> inf_stock_id { get; set; }
    
        // Navigation properties
    
        public virtual tb_InformeStock tb_InformeStock { get; set; }
        public virtual tb_Insumos tb_Insumos { get; set; }
    
    }
}
