//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Orina_Complementarios
    {
        public tb_Analisis_Orina_Complementarios()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        public int id_orina_complement { get; set; }
        public Nullable<decimal> moluria { get; set; }
        public Nullable<decimal> cloruros_natruria_potasuria { get; set; }
        public Nullable<decimal> sodio { get; set; }
        public Nullable<decimal> potasio { get; set; }
        public Nullable<decimal> fosforo { get; set; }
        public Nullable<decimal> calcio { get; set; }
        public Nullable<decimal> urea { get; set; }
        public Nullable<decimal> acido_urico { get; set; }
        public Nullable<decimal> proteinas { get; set; }
        public Nullable<decimal> acido_homogentisico_oxidasa { get; set; }
        public Nullable<decimal> proteinas_bencejones { get; set; }
        public Nullable<decimal> creatinina { get; set; }
        public Nullable<decimal> oxalato_calcico { get; set; }
        public Nullable<decimal> lipidos { get; set; }
        public Nullable<decimal> volumen_total { get; set; }
        public Nullable<decimal> recuento_addis_hematies { get; set; }
        public Nullable<decimal> recuento_addis_leucositos { get; set; }
        public Nullable<decimal> recuento_addis_cilindros { get; set; }
        public Nullable<decimal> rto_cuantitativo_elem_figurados_totales_hematies { get; set; }
        public Nullable<decimal> rto_cuantitativo_elem_figurados_totales_leucositos { get; set; }
        public Nullable<decimal> rto_cuantitativo_elem_figurados_totales_cilindros_hialinos { get; set; }
        public Nullable<int> examen_orina_id { get; set; }
        public Nullable<int> estado_id { get; set; }
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
        public virtual tb_Analisis_Orina_Completa tb_Analisis_Orina_Completa { get; set; }
    }
}
