//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Analisis_Hemostacia_Coagulacion
    {
        public tb_Analisis_Hemostacia_Coagulacion()
        {
            this.tb_Analisis = new HashSet<tb_Analisis>();
        }
    
        public int id_emostacia_y_coag { get; set; }
        public Nullable<decimal> recuento_plaquetas { get; set; }
        public Nullable<System.TimeSpan> tiempo_coagulacion { get; set; }
        public Nullable<System.TimeSpan> tiempo_sangria { get; set; }
        public Nullable<System.TimeSpan> tiempo_recalcificacion { get; set; }
        public Nullable<System.TimeSpan> tiempo_protombina_quick { get; set; }
        public Nullable<System.TimeSpan> tiempo_trombina { get; set; }
        public Nullable<decimal> kptt { get; set; }
        public Nullable<System.TimeSpan> tiempo_cafeina { get; set; }
        public Nullable<System.TimeSpan> tiempo_retraccion_coagulo { get; set; }
        public Nullable<decimal> fibrinogeno { get; set; }
        public Nullable<decimal> prueba_rumpel_leedle { get; set; }
        public Nullable<decimal> protrombina_residual_serica { get; set; }
        public Nullable<decimal> determinacion_fribrinolisis_fibrinolisina { get; set; }
        public Nullable<decimal> lisis_de_las_euglobinas { get; set; }
        public string investig_anticoagulantes { get; set; }
        public Nullable<decimal> productos_de_degradacion_fibrinogeno { get; set; }
        public Nullable<int> analisis_id { get; set; }
        public Nullable<int> estado_id { get; set; }
    
        public virtual ICollection<tb_Analisis> tb_Analisis { get; set; }
        public virtual tb_Estado_Analisis tb_Estado_Analisis { get; set; }
    }
}
