//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compra_Detalle
    {
        public int id_compra_detalle { get; set; }
        public Nullable<int> compra_id { get; set; }
        public Nullable<int> insumo_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> subtotal_prod_cant { get; set; }
    
        public virtual tb_Compras tb_Compras { get; set; }
        public virtual tb_Insumos tb_Insumos { get; set; }
    }
}
