//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compra_Detalle
    {
        // Primitive properties
    
        public int id_compra_detalle { get; set; }
        public Nullable<int> compra_id { get; set; }
        public Nullable<int> insumo_id { get; set; }
        public string medida { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<double> subtotal_prod_cant { get; set; }
        public Nullable<decimal> total { get; set; }
    
        // Navigation properties
    
        public virtual tb_Compras tb_Compras { get; set; }
        public virtual tb_Insumos tb_Insumos { get; set; }
    
    }
}
