//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Compras
    {
        public tb_Compras()
        {
            this.tb_Compra_Detalle = new HashSet<tb_Compra_Detalle>();
        }
    
        public int id_compra { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> notapedido_id { get; set; }
    
        public virtual ICollection<tb_Compra_Detalle> tb_Compra_Detalle { get; set; }
        public virtual tb_NotaPedido tb_NotaPedido { get; set; }
    }
}
