//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Donantes
    {
        public tb_Donantes()
        {
            this.tb_Direcciones_x_Donante = new HashSet<tb_Direcciones_x_Donante>();
            this.tb_Telefono_x_Donante = new HashSet<tb_Telefono_x_Donante>();
            this.tb_Email_x_donante = new HashSet<tb_Email_x_donante>();
            this.tb_Pacientes1 = new HashSet<tb_Pacientes>();
        }
    
        public int id_donante { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> dni { get; set; }
        public Nullable<int> grupo_sanguineo_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> paciente_id { get; set; }
    
        public virtual ICollection<tb_Direcciones_x_Donante> tb_Direcciones_x_Donante { get; set; }
        public virtual ICollection<tb_Telefono_x_Donante> tb_Telefono_x_Donante { get; set; }
        public virtual ICollection<tb_Email_x_donante> tb_Email_x_donante { get; set; }
        public virtual tb_GrupoSanguineo tb_GrupoSanguineo { get; set; }
        public virtual tb_Pacientes tb_Pacientes { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes1 { get; set; }
    }
}
