//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DireccionObraSocial
    {
        public tb_DireccionObraSocial()
        {
            this.tb_Direccion_x_ObraSocial = new HashSet<tb_Direccion_x_ObraSocial>();
        }
    
        public int id_direccion { get; set; }
        public string calle { get; set; }
        public string barrio { get; set; }
        public Nullable<int> provincia { get; set; }
        public Nullable<int> localidad { get; set; }
    
        public virtual ICollection<tb_Direccion_x_ObraSocial> tb_Direccion_x_ObraSocial { get; set; }
    }
}
