//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Diagnosticos
    {
        public int id_diagnostico { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> borrado { get; set; }
        public string detalle { get; set; }
    
        public virtual tb_Pacientes tb_Pacientes { get; set; }
    }
}
