//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Donantes
    {
        public tb_Donantes()
        {
            this.tb_Pacientes1 = new HashSet<tb_Pacientes>();
            this.tb_DireccionTodos = new HashSet<tb_DireccionTodos>();
            this.tb_EmailsTodos = new HashSet<tb_EmailsTodos>();
            this.tb_TelefonosTodos = new HashSet<tb_TelefonosTodos>();
        }
    
        // Primitive properties
    
        public int id_donante { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> dni { get; set; }
        public Nullable<int> grupo_sanguineo_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<int> paciente_id { get; set; }
        public Nullable<int> borrado { get; set; }
    
        // Navigation properties
    
        public virtual tb_GrupoSanguineo tb_GrupoSanguineo { get; set; }
        public virtual tb_Pacientes tb_Pacientes { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes1 { get; set; }
        public virtual ICollection<tb_DireccionTodos> tb_DireccionTodos { get; set; }
        public virtual ICollection<tb_EmailsTodos> tb_EmailsTodos { get; set; }
        public virtual ICollection<tb_TelefonosTodos> tb_TelefonosTodos { get; set; }
    
    }
}
