//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Direccion_x_ObraSocial
    {
        public int id_dir { get; set; }
        public Nullable<int> obra_social_id { get; set; }
        public Nullable<int> direccion_id { get; set; }
    
        public virtual tb_DireccionObraSocial tb_DireccionObraSocial { get; set; }
        public virtual tb_ObraSocial tb_ObraSocial { get; set; }
    }
}
