//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Direccion_x_Medico
    {
        public int id_dir_x_medico { get; set; }
        public Nullable<int> medico_id { get; set; }
        public Nullable<int> direccion_id { get; set; }
    
        public virtual tb_DireccionTodos tb_DireccionTodos { get; set; }
        public virtual tb_Medicos tb_Medicos { get; set; }
    }
}
