//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_EmailsTodos
    {
        public tb_EmailsTodos()
        {
            this.tb_Email_x_donante = new HashSet<tb_Email_x_donante>();
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        public int id_email { get; set; }
        public Nullable<int> borrado { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<tb_Email_x_donante> tb_Email_x_donante { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    }
}
