//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GrupoSanguineo
    {
        public tb_GrupoSanguineo()
        {
            this.tb_Donantes = new HashSet<tb_Donantes>();
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        public int id_grupo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<tb_Donantes> tb_Donantes { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    }
}
