//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Insumos
    {
        public tb_Insumos()
        {
            this.tb_Compra_Detalle = new HashSet<tb_Compra_Detalle>();
            this.tb_Alarmas_Stock = new HashSet<tb_Alarmas_Stock>();
            this.tb_InformeStock = new HashSet<tb_InformeStock>();
            this.Pedido_Detalle = new HashSet<Pedido_Detalle>();
        }
    
        public int id_insumo { get; set; }
        public string detalle { get; set; }
        public Nullable<int> cant_minima { get; set; }
        public Nullable<int> medida { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
        public Nullable<int> cant_disponible { get; set; }
        public Nullable<int> tipo_id { get; set; }
        public Nullable<int> marca_id { get; set; }
        public Nullable<int> borrado { get; set; }
    
        public virtual ICollection<tb_Compra_Detalle> tb_Compra_Detalle { get; set; }
        public virtual tb_Insumo_Marca tb_Insumo_Marca { get; set; }
        public virtual tb_Medida_Insumo tb_Medida_Insumo { get; set; }
        public virtual tb_Tipo_Insumo tb_Tipo_Insumo { get; set; }
        public virtual ICollection<tb_Alarmas_Stock> tb_Alarmas_Stock { get; set; }
        public virtual ICollection<tb_InformeStock> tb_InformeStock { get; set; }
        public virtual ICollection<Pedido_Detalle> Pedido_Detalle { get; set; }
    }
}
