//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_IVA
    {
        public tb_IVA()
        {
            this.tb_Factura = new HashSet<tb_Factura>();
        }
    
        public int id_iva { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual ICollection<tb_Factura> tb_Factura { get; set; }
    }
}
