//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Medico_Tipo
    {
        public tb_Medico_Tipo()
        {
            this.tb_Medicos = new HashSet<tb_Medicos>();
        }
    
        public int id_tipo_medico { get; set; }
        public string detalle { get; set; }
    
        public virtual ICollection<tb_Medicos> tb_Medicos { get; set; }
    }
}
