//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Medicos
    {
        public tb_Medicos()
        {
            this.tb_Direccion_x_Medico = new HashSet<tb_Direccion_x_Medico>();
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        public int id_medico { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> dni { get; set; }
        public Nullable<int> especialidad { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public Nullable<int> borrado { get; set; }
    
        public virtual ICollection<tb_Direccion_x_Medico> tb_Direccion_x_Medico { get; set; }
        public virtual tb_Medico_Tipo tb_Medico_Tipo { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    }
}
