//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Medico_Tipo
    {
        public tb_Medico_Tipo()
        {
            this.tb_Medicos = new HashSet<tb_Medicos>();
        }
    
        // Primitive properties
    
        public int id_tipo_medico { get; set; }
        public string detalle { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Medicos> tb_Medicos { get; set; }
    
    }
}
