//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NotaPedido
    {
        public tb_NotaPedido()
        {
            this.tb_Compras = new HashSet<tb_Compras>();
        }
    
        public int id_nota_pedido { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> informeStock_id { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<tb_Compras> tb_Compras { get; set; }
        public virtual tb_InformeStock tb_InformeStock { get; set; }
    }
}
