//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NotaPedido
    {
        public tb_NotaPedido()
        {
            this.Pedido_Detalle = new HashSet<Pedido_Detalle>();
            this.tb_Compras = new HashSet<tb_Compras>();
        }
    
        // Primitive properties
    
        public int id_nota_pedido { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public Nullable<int> informeStock_id { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> proveedor { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<int> pago { get; set; }
        public int numero_orden { get; set; }
        public string descripcion { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<Pedido_Detalle> Pedido_Detalle { get; set; }
        public virtual ICollection<tb_Compras> tb_Compras { get; set; }
        public virtual tb_InformeStock tb_InformeStock { get; set; }
    
    }
}
