//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sexo
    {
        public tb_Sexo()
        {
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        // Primitive properties
    
        public int id_sexo { get; set; }
        public string descripcion { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    
    }
}
