//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TelefonosTodos
    {
        public tb_TelefonosTodos()
        {
            this.tb_Telefono_x_Donante = new HashSet<tb_Telefono_x_Donante>();
            this.tb_Telefonos_x_ObraSocial = new HashSet<tb_Telefonos_x_ObraSocial>();
            this.tb_Pacientes = new HashSet<tb_Pacientes>();
        }
    
        public int id_telefono { get; set; }
        public string telefono { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<tb_Telefono_x_Donante> tb_Telefono_x_Donante { get; set; }
        public virtual ICollection<tb_Telefonos_x_ObraSocial> tb_Telefonos_x_ObraSocial { get; set; }
        public virtual ICollection<tb_Pacientes> tb_Pacientes { get; set; }
    }
}
