//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Telefono_x_Donante
    {
        public int id_tel_x_donante { get; set; }
        public Nullable<int> donante_id { get; set; }
        public Nullable<int> telefono_id { get; set; }
    
        public virtual tb_Donantes tb_Donantes { get; set; }
        public virtual tb_TelefonosTodos tb_TelefonosTodos { get; set; }
    }
}
