//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Pago
    {
        // Primitive properties
    
        public int id_pago { get; set; }
        public string detalle { get; set; }
        public string comentario { get; set; }
    
    }
}
